name = "quickshare-worker"
account_id = "cca975e0235380701243fcb6f5e66e97"

[vars]
ENVIRONMENT = "production"
BASE_URL = "https://your-subdomain.workers.dev"


# Optional: configure a custom domain in Cloudflare.
# [[routes]]
# pattern = "your-domain.com"
# custom_domain = true

# Optional: only needed if you re-enable file uploads.
# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "pastes"

[[d1_databases]]
binding = "DB"
database_name = "quickshare"
database_id = "891b8de7-fad5-4334-ac41-b192e2b7d334"
migrations_dir = "./drizzle"
